# Generated by Django 4.2.3 on 2023-07-10 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alterapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='datatable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='photos')),
                ('description', models.TextField()),
            ],
        ),
    ]
